"use client";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Plus, ReceiptText, WalletCards } from "lucide-react";
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Area, AreaChart } from "recharts";
import { format } from "date-fns";
import { getMonthAnalytics, createInsights } from "@/lib/analytics";
import { formatMoney } from "@/lib/money";
import { useSpendMate } from "./demo-provider";

function Summary({label,value,tone,icon:Icon}:{label:string;value:string;tone:string;icon:typeof ArrowUpRight}) { return <div className="card" style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start"}}><span className="muted" style={{fontWeight:700,fontSize:".86rem"}}>{label}</span><span style={{display:"grid",placeItems:"center",width:32,height:32,borderRadius:10,background:tone,color:"var(--brand)"}}><Icon size={17}/></span></div><strong style={{display:"block",fontSize:"1.48rem",letterSpacing:"-.04em",marginTop:20}}>{value}</strong></div>; }
export function Dashboard() { const {user,transactions,categories,methods}=useSpendMate(); const now=new Date(); const analytics=getMonthAnalytics(transactions,categories,methods,now); const prior=getMonthAnalytics(transactions,categories,methods,new Date(now.getFullYear(),now.getMonth()-1,1)); const insights=createInsights(analytics,prior); const recent=transactions.filter(t=>!t.deletedAt).slice(0,5);
 return <><section style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"end",flexWrap:"wrap",marginBottom:24}}><div><p className="eyebrow">{format(now,"MMMM yyyy")}</p><h1 className="page-title">Good {now.getHours()<12?"morning":now.getHours()<17?"afternoon":"evening"}, {user?.name.split(" ")[0]}</h1><p className="muted" style={{margin:0}}>Here’s a clear view of your month.</p></div><Link className="btn btn-primary" href="/add"><Plus size={18}/> Add transaction</Link></section>
 <div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(175px,1fr))",marginBottom:18}}><Summary label="Money received" value={formatMoney(analytics.credits)} tone="#e7f6ee" icon={ArrowUpRight}/><Summary label="Money spent" value={formatMoney(analytics.debits)} tone="#fff0eb" icon={ArrowDownRight}/><Summary label="Net cash flow" value={formatMoney(analytics.net)} tone="#edf5ff" icon={WalletCards}/><Summary label="Transactions" value={String(analytics.count)} tone="#f3efff" icon={ReceiptText}/></div>
 {analytics.count===0 ? <div className="card" style={{padding:"55px 25px",textAlign:"center"}}><h2 style={{margin:0}}>Your spending story starts here.</h2><p className="muted">Add your first transaction and we’ll start showing you where your money goes.</p><Link className="btn btn-primary" href="/add">Add transaction</Link></div> : <div className="grid" style={{gridTemplateColumns:"minmax(0,1.25fr) minmax(290px,.75fr)",alignItems:"start"}}><section className="card" style={{padding:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2 style={{fontSize:"1.05rem",margin:0}}>Spending trend</h2><p className="muted" style={{fontSize:".85rem",margin:"5px 0 0"}}>Your debit spending this month</p></div></div><div style={{height:260,marginTop:12}}><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics.dailyTotals}><defs><linearGradient id="spend" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#1e8b62" stopOpacity=".32"/><stop offset="1" stopColor="#1e8b62" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="day" tickLine={false} axisLine={false} fontSize={12}/><YAxis tickFormatter={(v)=>`₹${v/100}`} tickLine={false} axisLine={false} fontSize={12}/><Tooltip formatter={(v)=>formatMoney(Number(v))}/><Area dataKey="amount" stroke="#1e8b62" fill="url(#spend)" strokeWidth={2.5}/></AreaChart></ResponsiveContainer></div></section>
 <section className="card" style={{padding:20}}><h2 style={{fontSize:"1.05rem",margin:0}}>Smart insight</h2><div style={{display:"grid",gap:10,marginTop:15}}>{(insights.length?insights:["Add a few more transactions to unlock your monthly insight."]).map(insight=><div key={insight} style={{padding:14,borderRadius:13,background:"var(--brand-soft)",lineHeight:1.45,fontSize:".92rem"}}>{insight}</div>)}</div></section>
 <section className="card" style={{padding:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2 style={{fontSize:"1.05rem",margin:0}}>Spending by category</h2><p className="muted" style={{fontSize:".85rem",margin:"5px 0 0"}}>Only debit transactions</p></div><Link href="/insights" style={{color:"var(--brand)",fontWeight:700,fontSize:".88rem"}}>See insights</Link></div><div style={{height:190,marginTop:10}}><ResponsiveContainer><PieChart><Pie data={analytics.categoryTotals} dataKey="amount" nameKey="name" innerRadius={52} outerRadius={78} paddingAngle={3}>{analytics.categoryTotals.map((entry)=><Cell key={entry.name} fill={entry.color}/>)}</Pie><Tooltip formatter={(v)=>formatMoney(Number(v))}/></PieChart></ResponsiveContainer></div><div style={{display:"grid",gap:9}}>{analytics.categoryTotals.slice(0,4).map(c=><div key={c.name} style={{display:"flex",justifyContent:"space-between",fontSize:".88rem"}}><span style={{display:"flex",gap:8,alignItems:"center"}}><i style={{width:8,height:8,borderRadius:"50%",background:c.color}}/>{c.name}</span><strong>{formatMoney(c.amount)}</strong></div>)}</div></section>
 <section className="card" style={{padding:20}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><h2 style={{fontSize:"1.05rem",margin:0}}>Recent activity</h2><Link href="/transactions" style={{color:"var(--brand)",fontWeight:700,fontSize:".88rem"}}>View all</Link></div><div style={{marginTop:10}}>{recent.map(t=>{const category=categories.find(c=>c.id===t.categoryId)?.name ?? "Uncategorized";return <Link href={`/transactions/${t.id}`} key={t.id} style={{display:"flex",padding:"13px 0",borderBottom:"1px solid var(--line)",justifyContent:"space-between",alignItems:"center"}}><div><strong style={{fontSize:".93rem"}}>{t.merchant||category}</strong><div className="muted" style={{fontSize:".8rem",marginTop:3}}>{category} · {methods.find(m=>m.id===t.paymentMethodId)?.name}</div></div><strong style={{color:t.type==="DEBIT"?"var(--ink)":"var(--brand)"}}>{t.type==="DEBIT"?"−":"+"}{formatMoney(t.amountMinor)}</strong></Link>})}</div></section></div>}</>;
}
