"use client";
import { useState } from "react";
import Link from "next/link";
import { Plus, Trash2 } from "lucide-react";
import { AppShell } from "./app-shell";
import { useSpendMate } from "./demo-provider";

type Section = "profile" | "categories" | "payment-methods" | "privacy";
export function SettingsPage({ section = "profile" }: { section?: Section }) {
  const { user, categories, methods, addCategory, renameCategory, addMethod, logout, clearRecent } = useSpendMate();
  const [name, setName] = useState(""); const isCats = section === "categories"; const isMethods = section === "payment-methods";
  const nav = [["/settings", "Profile"], ["/settings/categories", "Categories"], ["/settings/payment-methods", "Payment methods"], ["/settings/privacy", "Privacy"]];
  const add = () => { if (!name.trim()) return; if (isCats) addCategory(name); else addMethod(name); setName(""); };
  const management = <div className="card" style={{ padding: 20 }}><div style={{ display: "flex", gap: 10, marginBottom: 17 }}><input className="field" value={name} onChange={(event) => setName(event.target.value)} placeholder={`New ${isCats ? "category" : "payment method"}`} /><button className="btn btn-primary" onClick={add}><Plus size={17} /> Add</button></div><div style={{ display: "grid", gap: 8 }}>{(isCats ? categories : methods).map((item) => <div key={item.id} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: 12, borderRadius: 11, background: "#f7faf8" }}><strong>{item.name}</strong>{isCats ? <button className="btn btn-secondary" style={{ padding: "6px 9px", fontSize: ".78rem" }} onClick={() => { const next = prompt("Rename category", item.name); if (next) renameCategory(item.id, next); }}>Rename</button> : <span className="muted" style={{ fontSize: ".8rem" }}>Active</span>}</div>)}</div></div>;
  const privacy = <div className="grid"><div className="card" style={{ padding: 20 }}><h2 style={{ fontSize: "1.05rem", marginTop: 0 }}>Screenshots</h2><p className="muted">Screenshots are private attachments. You can delete them without deleting their related transaction.</p><button className="btn btn-secondary" onClick={() => alert("No locally stored screenshot attachments to delete.")}>Delete screenshots</button></div><div className="card" style={{ padding: 20 }}><h2 style={{ fontSize: "1.05rem", marginTop: 0 }}>Your data</h2><p className="muted">Export is available in the configured Supabase production environment. This preview keeps data only in this browser.</p><button className="btn btn-secondary" onClick={clearRecent}>Clear recent choices</button></div><div className="card" style={{ padding: 20, borderColor: "#f2c9c9" }}><h2 style={{ fontSize: "1.05rem", marginTop: 0 }}>Delete account</h2><p className="muted">Production deletion cascades to user transactions, preferences, and attachments.</p><button className="btn btn-danger" onClick={() => { if (confirm("Log out and clear this preview account?")) { localStorage.removeItem("spendmate-local-v1"); logout(); } }}><Trash2 size={17} /> Delete preview account</button></div></div>;
  const profile = <div className="card" style={{ padding: 22 }}><h2 style={{ fontSize: "1.05rem", marginTop: 0 }}>Account</h2><div className="grid" style={{ gridTemplateColumns: "1fr 1fr" }}><div><span className="muted" style={{ fontSize: ".82rem" }}>Name</span><strong style={{ display: "block", marginTop: 5 }}>{user?.name}</strong></div><div><span className="muted" style={{ fontSize: ".82rem" }}>Email</span><strong style={{ display: "block", marginTop: 5 }}>{user?.email}</strong></div></div><hr style={{ border: 0, borderTop: "1px solid var(--line)", margin: "24px 0" }} /><h2 style={{ fontSize: "1.05rem" }}>Preferences</h2><div className="grid" style={{ gridTemplateColumns: "1fr 1fr" }}><label><span className="label">Currency</span><select className="field"><option>Indian Rupee (₹)</option></select></label><label><span className="label">Default transaction type</span><select className="field"><option>Debit (Money out)</option><option>Credit (Money in)</option></select></label></div><button className="btn btn-secondary" style={{ marginTop: 28 }} onClick={logout}>Log out</button></div>;
  return <AppShell><div style={{ maxWidth: 800 }}><p className="eyebrow">Settings</p><h1 className="page-title">{section === "profile" ? "Profile & preferences" : isCats ? "Categories" : isMethods ? "Payment methods" : "Privacy & data"}</h1><nav style={{ display: "flex", gap: 8, overflowX: "auto", margin: "18px 0" }}>{nav.map(([href, label]) => <Link className={`nav-link ${(section === "profile" && href === "/settings") || href.endsWith(section) ? "active" : ""}`} href={href} key={href}>{label}</Link>)}</nav>{isCats || isMethods ? management : section === "privacy" ? privacy : profile}</div></AppShell>;
}
