"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { format, parseISO } from "date-fns";
import { Search, SlidersHorizontal } from "lucide-react";
import { formatMoney } from "@/lib/money";
import { useSpendMate } from "./demo-provider";

export function TransactionList() { const {transactions,categories,methods}=useSpendMate(); const [search,setSearch]=useState("");const [category,setCategory]=useState("");const [method,setMethod]=useState("");const [kind,setKind]=useState(""); const grouped=useMemo(()=>transactions.filter(t=>!t.deletedAt).filter(t=>!search||[t.merchant,t.note,categories.find(c=>c.id===t.categoryId)?.name,methods.find(m=>m.id===t.paymentMethodId)?.name].join(" ").toLowerCase().includes(search.toLowerCase())).filter(t=>!category||t.categoryId===category).filter(t=>!method||t.paymentMethodId===method).filter(t=>!kind||t.type===kind).sort((a,b)=>b.transactionDate.localeCompare(a.transactionDate)).reduce<Record<string,typeof transactions>>((acc,t)=>{(acc[t.transactionDate]??=[]).push(t);return acc;},{}),[transactions,search,category,method,kind,categories,methods]);
 return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16,flexWrap:"wrap"}}><div><p className="eyebrow">History</p><h1 className="page-title">Transactions</h1><p className="muted">Find, review, and keep your records tidy.</p></div><Link href="/add" className="btn btn-primary">Add transaction</Link></div><div className="card" style={{padding:14,margin:"24px 0 16px"}}><div style={{display:"flex",gap:8,alignItems:"center"}}><Search size={18} className="muted"/><input className="field" style={{border:0,padding:7}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search merchant, category, or note"/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:9,borderTop:"1px solid var(--line)",paddingTop:12,marginTop:10}}><select className="field" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className="field" value={method} onChange={e=>setMethod(e.target.value)}><option value="">All methods</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><select className="field" value={kind} onChange={e=>setKind(e.target.value)}><option value="">Credit & debit</option><option value="DEBIT">Money out</option><option value="CREDIT">Money in</option></select></div></div>{Object.keys(grouped).length===0?<div className="card" style={{padding:45,textAlign:"center"}}><SlidersHorizontal size={28} color="var(--brand)"/><h2>No transactions found</h2><p className="muted">Try clearing a filter or add a new transaction.</p></div>:<div style={{display:"grid",gap:20}}>{Object.entries(grouped).map(([date,items])=><section key={date}><h2 style={{fontSize:".95rem",margin:"0 0 9px",color:"var(--muted)"}}>{format(parseISO(date),"d MMMM")}</h2><div className="card" style={{padding:"0 17px"}}>{items.map(t=>{const c=categories.find(x=>x.id===t.categoryId)?.name??"Uncategorized";const p=methods.find(x=>x.id===t.paymentMethodId)?.name??"Unknown";return <Link href={`/transactions/${t.id}`} key={t.id} style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",padding:"15px 0",borderBottom:"1px solid var(--line)"}}><div><strong>{t.merchant||c}</strong><p className="muted" style={{fontSize:".83rem",margin:"4px 0 0"}}>{c} · {p}{t.note?` · ${t.note}`:""}</p></div><strong style={{whiteSpace:"nowrap",color:t.type==="CREDIT"?"var(--brand)":"var(--ink)"}}>{t.type==="CREDIT"?"+":"−"}{formatMoney(t.amountMinor)}</strong></Link>})}</div></section>)}</div>}</>;
}
